FROM gcc:latest
RUN apt-get update && apt-get -y install build-essential iproute2 libboost-dev

COPY . /prime-client/

WORKDIR /prime-client/src
RUN make client

WORKDIR /prime-client/bin

CMD ./client -l $IP -i $CLIENT_NUM -s $SERVER_NUM -p $PORT
