version: '2'

services:
  prime_1:
    container_name: prime_1
    image: ggjinaj/prime:latest
    environment:
      - SERVER_NUM=1
      - MICROSECONDS=300
      - STEP=30
      - PP_TYPE=0
      - DELAY=0
    ports:
     - "7103:7103"
    networks:
      prime_net_1:
        ipv4_address: 192.168.55.3

  prime_2:
    container_name: prime_2
    image: ggjinaj/prime:latest
    environment:
      - SERVER_NUM=2
      - MICROSECONDS=300
      - STEP=30
      - PP_TYPE=0
      - DELAY=0
    ports:
     - "7104:7104"
    networks:
      prime_net_1:
        ipv4_address: 192.168.55.4

  prime_3:
    container_name: prime_3
    image: ggjinaj/prime:latest
    environment:
      - SERVER_NUM=3
      - MICROSECONDS=300
      - STEP=30
      - PP_TYPE=0
      - DELAY=0
    ports:
     - "7105:7105"
    networks:
      prime_net_1:
        ipv4_address: 192.168.55.5
  
  prime_4:
    container_name: prime_4
    image: ggjinaj/prime:latest
    environment:
      - SERVER_NUM=4
      - MICROSECONDS=300
      - STEP=30
      - PP_TYPE=0
      - DELAY=0
    ports:
     - "7106:7106"
    networks:
      prime_net_1:
        ipv4_address: 192.168.55.6

  client_1:
    container_name: prime_c1
    image: ggjinaj/prime_c
    environment:
      - IP=192.168.55.7
      - CLIENT_NUM=5
      - SERVER_NUM=1
      - PORT=8081
      - NUM_CLIENTS_TO_EMULATE=200
    ports:
     - "8081:8081"
    networks:
      prime_net_1:
        ipv4_address: 192.168.55.7
    depends_on:
     - prime_1

  client_2:
    container_name: prime_c2
    image: ggjinaj/prime_c
    environment:
      - IP=192.168.55.8
      - CLIENT_NUM=6
      - SERVER_NUM=2
      - PORT=8082
      - NUM_CLIENTS_TO_EMULATE=200
    ports:
     - "8082:8082"
    networks:
      prime_net_1:
        ipv4_address: 192.168.55.8
    depends_on:
     - prime_2
     
  client_3:
    container_name: prime_c3
    image: ggjinaj/prime_c
    environment:
      - IP=192.168.55.9
      - CLIENT_NUM=7
      - SERVER_NUM=3
      - PORT=8083
      - NUM_CLIENTS_TO_EMULATE=100
    ports:
     - "8083:8083"
    networks:
      prime_net_1:
        ipv4_address: 192.168.55.9
    depends_on:
     - prime_3

  client_4:
    container_name: prime_c4
    image: ggjinaj/prime_c
    environment:
      - IP=192.168.55.10
      - CLIENT_NUM=8
      - SERVER_NUM=4
      - PORT=8084
      - NUM_CLIENTS_TO_EMULATE=50
    ports:
     - "8084:8084"
    networks:
      prime_net_1:
        ipv4_address: 192.168.55.10
    depends_on:
     - prime_4

networks:
  prime_net_1:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.55.0/24
         gateway: 192.168.55.1
